### ISSUE TITLE
Incorrect test - getNextPosition(snake)

### ISSUE THREAD

**Issue by Matthieu-Riou** [epgfm/tuto6#2]
>  >>> getNextPosition([[0, 0], [1, 0], 'red', True, 1])
    (1, 0)
    >>> getNextPosition([[0, 0], [0, 1], 'red', True, 1])
    (0, 1)

Just return the speed vector (snake[1]) validates all the tests, because we only test with a starting position at [0,0].

**Comment by epgfm** [comment]
Can you propose a test to defeat this incorrect implementation?

**Comment by Matthieu-Riou** [comment]
Yes I can

**Comment by Matthieu-Riou** [comment]
Sorry, I'm so funny.

>\>\>\> getNextPosition([[4, 0], [-1,0], 'red', True, 1])
(3,0)

**Comment by epgfm** [comment]
https://github.com/epgfm/tuto6/commit/ead8941c5975554bbda0cd861b69f78c9e31d7f1

Thanks
