### ISSUE TITLE
Incomplet test - updateGrid

### ISSUE THREAD

**Issue by Matthieu-Riou** [epgfm/tuto6#3]
Despite specification, doesn't test the dead snake case.

> \>\>\> killSnake(s); updateGrid(g, s) ; displayGrid(g)

I should return a grid without any *. I can draw it here, because github doesn't handle well pixel art.

**Comment by epgfm** [comment]
https://github.com/epgfm/tuto6/commit/5b2170135af393e112339570799b2e6fb9a5cd80

Thanks
